package spaghettichef.camera;

public enum FrameAnalysisReason {

    ANALYSIS_COMPLETED,
    ANALYSIS_SKIPPED,
    MISSING_PREVIOUS_FRAME,
    MISSING_LATEST_FRAME,
    IMAGE_READ_FAILED,
    IMAGE_DIMENSION_MISMATCH,
    NO_COMPARABLE_PIXELS,
    LOW_VISUAL_DELTA,
    HIGH_VISUAL_DELTA,
    DELTA_IMAGE_WRITTEN,
    DELTA_IMAGE_WRITE_FAILED
}