package spaghettichef.job;

public enum JobFailureReason {
    PRECONDITION_FAILED,
    PRINTER_NOT_FOUND,
    PRINTER_DISABLED,
    PRINTER_BUSY,
    PRINTER_DISCONNECTED,
    INVALID_JOB_STATE,
    INVALID_PARAMETER,
    NO_RESPONSE,
    TIMEOUT,
    COMMUNICATION_FAILURE,
    PRINTER_REPORTED_FAILURE,
    UNEXPECTED_RESPONSE,
    SESSION_DESTABILIZED,
    CANCELLED_BY_OPERATOR,
    UNKNOWN
}