package printerhub.security;

public enum Permission {
    VIEW_DASHBOARD,
    VIEW_PRINTERS,
    VIEW_MONITORING,
    VIEW_JOBS,
    VIEW_HISTORY,
    VIEW_SETTINGS,
    CONFIGURE_PRINTERS,
    CONFIGURE_MONITORING,
    CONFIGURE_TRANSFER_SETTINGS,
    CONTROL_JOBS,
    MANAGE_PRINT_FILES,
    MANAGE_SD_CARD_FILES,
    UPLOAD_TO_SD_CARD,
    EXECUTE_SAFE_COMMANDS,
    EXECUTE_DANGEROUS_COMMANDS,
    MANAGE_SECURITY
}
