package spaghettichef;

public enum SerialFailureType {
    DEVICE_PATH_NOT_FOUND,
    DEVICE_PERMISSION_DENIED,
    DEVICE_BUSY,
    DEVICE_DISCONNECTED,
    CONNECT_TIMEOUT,
    READ_TIMEOUT,
    WRITE_FAILURE,
    PROTOCOL_ERROR,
    TEMPORARY_COMMUNICATION_FAILURE,
    UNKNOWN_SERIAL_FAILURE
}
